name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
        laravel: ["^8.0", "^9.0", "^10.0", "^11.0", "^12.0"]
        exclude:
          - laravel: "^12.0"
            php: 8.1
          - laravel: "^12.0"
            php: 8.0
          - laravel: "^12.0"
            php: 7.4
          - laravel: "^11.0"
            php: 8.1
          - laravel: "^11.0"
            php: 8.0
          - laravel: "^11.0"
            php: 7.4
          - laravel: "^10.0"
            php: 8.0
          - laravel: "^10.0"
            php: 7.4
          - laravel: "^9.0"
            php: 7.4
          - laravel: "^8.12"
            php: 8.3
          - laravel: "^8.12"
            php: 8.4
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
          
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader
      
      - name: Execute tests
        run: ./vendor/bin/phpunit --stop-on-failure
      
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github